- name: Playlevel variables
  hosts: local
  connection: local #connects to local host
  vars_files: 
   -source.yaml
  tasks:
  - name: Course details $$$
    debug:
      msg: " Course ::{{ course}}, Duration ::{{ duration }}, TRAINER :: {{ trainer }}"
      